[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = 'probe-rs run --chip RP2040 --protocol swd --probe 2e8a:000c:E6614103E763252F'

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
